# Generated by Django 4.2.7 on 2023-11-21 14:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_remove_author_biography'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featured',
            unique_together={('book', 'user')},
        ),
    ]
